import type { ThemeDefinition } from './contract';

/** Pop-art comic ink, Ben-Day print, paper panels and primary-color action. */
export default {
  id: 'boom-pow',
  name: 'Boom Pow',
  treatment: 'comic',
  tokens: {
    scheme: 'light',
    bg: '#079DDC',
    card: '#FFF8E8',
    ink: '#12120F',
    'card-ink': '#12120F',
    muted: '#514C40',
    line: '#12120F',
    edge: '#12120F',
    accent: '#0055AE',
    'primary-ink': '#FFF8E8',
    'primary-hover': '#003D7D',
    highlight: '#BD2018',
    control: '#FFF8E8',
    'control-ink': '#12120F',
    soft: '#FFE82F',
    low: '#992218',
    'low-bg': '#FFDCCB',
    correct: '#194A21',
    'correct-bg': '#BFECA4',
    high: '#992218',
    'high-bg': '#FFDCCB',
    danger: '#992218',
    'badge-bg': '#FFE82F',
    'help-bg': '#F2E8CF',
    track: '#CEC7B7',
    'focus-ring': '#0055AE',
    'notice-bg': '#FFE82F',
    'notice-ink': '#12120F',
    backdrop: '#12120FCC',
    'slider-track': '#CEC7B7',
    'slider-band': '#439638',
    'slider-handle': '#0055AE',
    'slider-target': '#BD2018',
    radius: '8px',
    'control-radius': '5px',
    'display-radius': '4px',
    'badge-radius': '2px',
    'help-radius': '4px',
    'toast-radius': '4px',
    'feedback-font': 'var(--heading-font)',
    'feedback-weight': '400',
    'feedback-transform': 'uppercase',
    'feedback-shadow': 'inset 0 0 0 2px var(--ink), 4px 4px 0 var(--ink)',
    'feedback-border': 'var(--ink)',
    'feedback-animation': 'feedback-pop 240ms cubic-bezier(0.16, 1, 0.3, 1)',
    'surface-border-style': 'solid',
    'panel-shadow': 'inset 0 0 0 2px #12120F, 4px 4px 0 #12120F',
    'surface-shadow': 'inset 0 0 0 2px #12120F, 5px 5px 0 #12120F',
    'button-shadow': 'inset 0 0 0 1px #12120F, 3px 3px 0 #12120F',
    'button-pressed-shadow': 'inset 0 0 0 2px #12120F, 1px 1px 0 #12120F',
    'page-pattern': 'none',
    'surface-pattern': 'none',
    'control-pattern': 'none',
    'heading-font': '"Boom Pow", Impact, sans-serif',
    'body-font': '"Trebuchet MS", system-ui, sans-serif',
    'data-font': '"Boom Pow", Impact, sans-serif',
    'label-font': '"Boom Pow", Impact, sans-serif',
    'heading-weight': '400',
    'heading-transform': 'uppercase',
    'heading-shadow': '2px 2px 0 #FFE82F',
    'label-weight': '400',
    'label-tracking': '0.035em',
    'label-transform': 'uppercase',
    'button-weight': '800',
    'note-shadow': 'none',
    'display-bg': '#FFF8E8',
    'display-ink': '#12120F',
    'display-shadow': 'inset 0 0 0 2px #12120F, 3px 3px 0 #12120F',
    'range-animation': 'range-glow 1.4s ease-in-out infinite alternate',
  },
} satisfies ThemeDefinition;
