import type { ThemeDefinition } from './contract';

/** Pitch Press: wood type on rag stock, archival black and live feedback inks.
 * Shared print decoration and bundled assets live in src/themes/pitch-press.css.
 */
export default {
  id: 'pitch-press',
  name: 'Pitch Press',
  treatment: 'print',
  tokens: {
    'range-animation': 'press-strike 220ms ease-out',
    scheme: 'light',
    bg: '#151515',
    card: '#FFF9EA',
    control: '#FFF9EA',
    ink: '#151515',
    muted: '#595348',
    line: '#9A907B',
    edge: '#151515',
    accent: '#151515',
    'primary-ink': '#FFF4D6',
    'primary-hover': '#39352F',
    soft: '#D8CFBA',
    highlight: '#151515',

    // Color is reserved for live pitch feedback; the broadside uses black and stock.
    low: '#932F22',
    'low-bg': '#FFE6DD',
    correct: '#294B32',
    'correct-bg': '#E2DBBD',
    high: '#183B60',
    'high-bg': '#E7ECFF',
    danger: '#A52716',
    'notice-bg': '#F2E8D0',
    'notice-ink': '#151515',
    'badge-bg': '#F2E8D0',
    'help-bg': '#F2E8D0',
    track: '#D8CFBA',
    'focus-ring': '#595348',
    backdrop: '#151515B3',
    'slider-track': '#D8CFBA',
    'slider-band': '#9A907B',
    'slider-handle': '#151515',
    'slider-target': '#151515',

    radius: '0px',
    'control-radius': '0px',
    'display-radius': '0px',
    'badge-radius': '0px',
    'help-radius': '0px',
    'toast-radius': '0px',
    'panel-shadow': 'inset 2px 2px 5px #15151526, 2px 3px 0 #151515',
    'surface-shadow': 'inset 2px 2px 5px #15151526',
    'button-shadow': '3px 4px 0 #151515',
    'surface-border-style': 'solid',

    // Bundled grain is applied by the theme stylesheet.
    'page-pattern': 'none',
    'surface-pattern': 'none',
    'control-pattern': 'none',
    'heading-font': '"Press Wood", "Press Slab", Georgia, serif',
    'body-font': '"Press Wood", Georgia, serif',
    'heading-style': 'normal',
    'heading-transform': 'uppercase',
    'heading-shadow': 'none',
    'note-shadow': 'none',
    'button-weight': '400',

    // Appearance extensions consumed by the shared CSS.
    'card-ink': '#151515',
    'control-ink': '#151515',
    'display-bg': '#F2E8D0',
    'display-ink': '#151515',
    'data-font': '"Courier New", Courier, monospace',
    'label-font': '"Press Wood", Georgia, serif',
    'heading-weight': '400',
    'label-weight': '400',
    'label-tracking': '0.04em',
    'label-transform': 'uppercase',
    'display-shadow': 'inset 2px 2px 5px #15151526',
    'button-pressed-shadow': '1px 1px 0 #151515',
  },
} satisfies ThemeDefinition;
